version: '3.2'
services:
  elasticsearch1:
    container_name: "elasticsearch1"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch1:/usr/share/elasticsearch/data:z
    #ports:
    #  - "9200:9200"
    #  - "9300:9300"
    environment:
      NODE_NAME: "elasticsearch1"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch0"
      NODE_NAME02: "elasticsearch1"
      NODE_NAME03: "elasticsearch2"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - "rabbitmq-prometheus"
  elasticsearch2:
    container_name: "elasticsearch2"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch2:/usr/share/elasticsearch/data:z
    #ports:
    #  - "9202:9200"
    #  - "9302:9300"
    environment:
      NODE_NAME: "elasticsearch2"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch0"
      NODE_NAME02: "elasticsearch1"
      NODE_NAME03: "elasticsearch2"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - "rabbitmq-prometheus"
  elasticsearch0:
    container_name: "elasticsearch0"
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch0:/usr/share/elasticsearch/data:z
    #ports:
    #  - "9203:9200"
    #  - "9303:9300"
    environment:
      NODE_NAME: "elasticsearch0"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch0"
      NODE_NAME02: "elasticsearch1"
      NODE_NAME03: "elasticsearch2"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    networks:
      - "rabbitmq-prometheus"

  kibana:
    container_name: "kibana"
    image: docker.elastic.co/kibana/kibana:7.15.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "['http://elasticsearch0:9200','http://elasticsearch1:9200','http://elasticsearch2:9200']"
    networks:
      - "rabbitmq-prometheus"
    depends_on:
      - elasticsearch0
      - elasticsearch1
      - elasticsearch2


networks:
  "rabbitmq-prometheus":

volumes:
 elasticsearch0:
 elasticsearch1:
 elasticsearch2:

