version: '3.2'

services:
  elasticsearch1:
    container_name: "elasticsearch1"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch1:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      NODE_NAME: "elasticsearch1"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch1"
      NODE_NAME02: "elasticsearch2"
      NODE_NAME03: "elasticsearch3"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    networks:
      - elk

  elasticsearch2:
    container_name: "elasticsearch2"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch2:/usr/share/elasticsearch/data:z
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      NODE_NAME: "elasticsearch2"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch1"
      NODE_NAME02: "elasticsearch2"
      NODE_NAME03: "elasticsearch3"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    networks:
      - elk

  elasticsearch3:
    container_name: "elasticsearch3"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch3:/usr/share/elasticsearch/data:z
    ports:
      - "9203:9200"
      - "9303:9300"
    environment:
      NODE_NAME: "elasticsearch3"
      CLUSTER_NAME: "elasticsearch_cluster"
      NODE_NAME01: "elasticsearch1"
      NODE_NAME02: "elasticsearch2"
      NODE_NAME03: "elasticsearch3"
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      # discovery.type: single-node
    networks:
      - elk
  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch1
      - elasticsearch2
      - elasticsearch3

networks:
  elk:
    driver: bridge

volumes:
 elasticsearch1:
 elasticsearch2:
 elasticsearch3:
