---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
monitoring.ui.container.elasticsearch.enabled: true
elasticsearch.hosts: ["http://elasticsearch0:9200","http://elasticsearch1:9200","http://elasticsearch2:9200"]

## X-Pack security credentials
#
elasticsearch.username: elastic
elasticsearch.password: changeme
